# Generated by Django 5.2.12 on 2026-04-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0005_classroomsession_screen_share_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomsession",
            name="student_chat_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="classroomsession",
            name="student_raise_hand_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
