# Generated by Django 5.2.12 on 2026-04-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0007_classroomsession_join_approval_enabled_joinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomsession",
            name="spotlight_mode",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("teacher", "Teacher"),
                    ("content", "Content"),
                ],
                default="off",
                max_length=16,
            ),
        ),
    ]
