# Generated by Django 5.2.12 on 2026-04-12 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0010_classroomsession_breakout_broadcast_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomsession",
            name="monitored_breakout_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitored_sessions",
                to="classrooms.breakoutroom",
            ),
        ),
    ]
