# Generated by Django 5.2.12 on 2026-04-13 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0013_classroomsession_last_breakout_layout"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="breakoutroom",
            name="spokesperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="breakout_spokesperson_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
