# Generated by Django 5.2.12 on 2026-04-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0014_breakoutroom_spokesperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomsession",
            name="delivery_mode",
            field=models.CharField(
                choices=[
                    ("interactive", "Interactive room"),
                    ("broadcast", "Broadcast lecture"),
                ],
                default="interactive",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="classroomsession",
            name="expected_participants",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
