# Generated by Django 5.2.12 on 2026-04-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0016_chat_qa_queue"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomsession",
            name="chat_slow_mode",
            field=models.BooleanField(
                default=False,
                help_text="When True, student main-room chat uses a stricter per-user rate limit.",
            ),
        ),
    ]
