# Generated by Django 5.2.12 on 2026-04-18 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0017_chat_slow_mode"),
        ("organizations", "0001_organization_hybrid_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomsession",
            name="open_enrollment",
            field=models.BooleanField(
                default=True,
                help_text="When True, learners with the room code can self-enroll.",
            ),
        ),
        migrations.AddField(
            model_name="classroomsession",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="enrollment_source",
            field=models.CharField(
                choices=[
                    ("roster", "Roster"),
                    ("join_code", "Join code"),
                    ("invite", "Invite"),
                ],
                default="roster",
                max_length=24,
            ),
        ),
    ]
