# Generated by Django 5.2.12 on 2026-04-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0020_program_resources_and_program_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionresource",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="session_resources/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="sessionresource",
            name="url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
