# Generated by Django 5.2.12 on 2026-04-12 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0004_pollvote_quizsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomsession",
            name="screen_share_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="classroomsession",
            name="stage_mode",
            field=models.CharField(
                choices=[
                    ("camera", "Camera"),
                    ("screenshare", "Screen share"),
                    ("whiteboard", "Whiteboard"),
                    ("slides", "Slides"),
                ],
                default="camera",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="classroomsession",
            name="teacher_camera_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="classroomsession",
            name="teacher_mic_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="classroomsession",
            name="whiteboard_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="WhiteboardState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pages", models.JSONField(blank=True, default=list)),
                ("active_page", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiteboard_state",
                        to="classrooms.classroomsession",
                    ),
                ),
            ],
        ),
    ]
