# Generated by Django 5.2.12 on 2026-04-12 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0008_classroomsession_spotlight_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomsession",
            name="breakout_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="classroomsession",
            name="recording_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="classroomsession",
            name="recording_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("recording", "Recording"),
                    ("paused", "Paused"),
                ],
                default="idle",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="BreakoutRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("sort_order", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breakout_rooms",
                        to="classrooms.classroomsession",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="breakout_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="classrooms.breakoutroom",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="breakout_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="classrooms.breakoutroom",
            ),
        ),
    ]
