# Generated by Django 5.2.12 on 2026-04-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0009_classroomsession_breakout_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomsession",
            name="breakout_broadcast_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="classroomsession",
            name="breakout_broadcast_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
