# Generated by Django 5.2.12 on 2026-04-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0011_classroomsession_monitored_breakout_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomsession",
            name="breakout_timer_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
