# Generated by Django 5.2.12 on 2026-04-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0012_classroomsession_breakout_timer_ends_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomsession",
            name="last_breakout_layout",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
