# Generated by Django 5.2.12 on 2026-04-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0015_classroomsession_delivery_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="qa_status",
            field=models.CharField(
                choices=[
                    ("none", "Not queued"),
                    ("pending", "Pending moderation"),
                    ("approved", "Approved to class chat"),
                    ("dismissed", "Dismissed"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="classroomsession",
            name="chat_moderation_mode",
            field=models.CharField(
                choices=[("open", "Open chat"), ("qa_queue", "Q&A moderation queue")],
                default="open",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="classroomsession",
            name="qa_queue_max_pending",
            field=models.PositiveIntegerField(default=75),
        ),
    ]
