# Generated by Django 5.2.1 on 2026-04-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_teacherprofile_youtube_oauth_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="school_class",
            field=models.CharField(blank=True, help_text="e.g. 4A, 4B", max_length=32),
        ),
    ]
